baseURL = "/"
languageCode = "en-us"
title = "willjasen"
theme = "LoveIt"
relativeURLS=true
googleAnalytics = "G-H5JWMTWEHQ"
enableRobotsTXT = true

[author]
  name = "willjasen"
  email = ""
  link = "/posts/welcome"

[menu]
  [[menu.main]]
      weight = 1
      identifier = "about"
      pre = ""
      post = ""
      name = "about"
      url = "/posts/welcome/"
      title = ""
  [[menu.main]]
      weight = 2
      identifier = "posts"
      pre = ""
      post = ""
      name = "posts"
      url = "/posts/"
      title = ""
  [[menu.main]]
      weight = 3
      identifier = "search"
      pre = ""
      post = ""
      name = "search"
      url = "/search/"
      title = ""

[params]
  title = "willjasen"
  description = "transhumanist and high functioning loser; instantiated simulation, statically stuck in superposition, calculated computationally complex, technomancer at will"
  images = ["/android-chrome-512x512.png"]
  [params.header]
    [params.header.title]
      name = "the webz"
      logo = "/profile_pic.jpg"
  [params.footer]
    copyright = false
    author = true
  [params.app]
    title = "willjasen"
    noFavicon = false
  [params.home]
    [params.home.profile]
      avatarURL = "/profile_pic.jpg"
      subtitle = "willjasen"
      social = true
    [params.home.posts]
        enable = true
        paginate = 10

  [params.verification]

  [params.seo]
    image = "/profile_pic.jpg"
    thumbnailUrl = "/profile_pic.jpg"

  [params.analytics]
  enable = true
    [params.analytics.google]
      id = "G-H5JWMTWEHQ"
      anonymizeIP = true

    [params.social]
      GitHub = "willjasen"
      Linkedin = "willjasen"
      Twitter = "willjasen"
      Instagram = "willjasen"
      Facebook = "willjasen"
      Keybase = "willjasen"
      Pinterest = "willjasen"
      Reddit = "willjasen"
      Snapchat = "willjasen"
      Soundcloud = "willjasen"
      Spotify = "willjasen"
      Paypal = "willjasen"
      Foursquare = "willjasen"
      # Steam = "willjasen"
      Twitch = "willjasen"
      Skype = "willjasen"
      Tumblr = "willjasen"
      Discord = "willjasen"
      # StableDiffusion = ""

    [params.page]
      [params.page.toc]
        enable = true
        keepStatic = false
        auto = true
      [params.page.seo]
        images = ["/profile_pic.jpg"]
        [params.page.seo.publisher]
          name = "willjasen"
          logoUrl = "/profile_pic.jpg"
        [params.page.share]
          enable = true
          Twitter = true
          Facebook = true
          Linkedin = true
          Whatsapp = false
          Pinterest = false
          Tumblr = true
          HackerNews = false
          Reddit = true
          VK = false
          Buffer = false
          Xing = false
          Line = false
          Instapaper = false
          Pocket = false
          Flipboard = false
          Weibo = false
          Blogger = false
          Baidu = false
          Odnoklassniki = false
          Evernote = true
          Skype = false
          Trello = true
          Mix = false

[outputs]
  home = ["HTML", "JSON"]